package com.biosimilarity.reflection.model.rlambda.Absyn; // Java Package generated by the BNF Converter.

public class AtomLiteral extends VariableExpr {
  public final String ident_;

  public AtomLiteral(String p1) { ident_ = p1; }

  public <R,A> R accept(com.biosimilarity.reflection.model.rlambda.Absyn.VariableExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.reflection.model.rlambda.Absyn.AtomLiteral) {
      com.biosimilarity.reflection.model.rlambda.Absyn.AtomLiteral x = (com.biosimilarity.reflection.model.rlambda.Absyn.AtomLiteral)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
