package com.biosimilarity.reflection.lib.ddl.tbldecl; // Java Package generated by the BNF Converter.

public class EntryPoint extends Expression {
  public final TableDecl tabledecl_;

  public EntryPoint(TableDecl p1) { tabledecl_ = p1; }

  public <R,A> R accept(com.biosimilarity.reflection.lib.ddl.tbldecl.Expression.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.reflection.lib.ddl.tbldecl.EntryPoint) {
      com.biosimilarity.reflection.lib.ddl.tbldecl.EntryPoint x = (com.biosimilarity.reflection.lib.ddl.tbldecl.EntryPoint)o;
      return this.tabledecl_.equals(x.tabledecl_);
    }
    return false;
  }

  public int hashCode() {
    return this.tabledecl_.hashCode();
  }


}
