package com.biosimilarity.reflection.lib.ddl.tbldecl; // Java Package generated by the BNF Converter.

public abstract class TableMethodDecl implements java.io.Serializable {
  public abstract <R,A> R accept(TableMethodDecl.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.reflection.lib.ddl.tbldecl.TblColCtorDecl p, A arg);
    public R visit(com.biosimilarity.reflection.lib.ddl.tbldecl.TblProjCtorDecl p, A arg);

  }

}
