package com.biosimilarity.reflection.lib.ddl.tbldecl; // Java Package generated by the BNF Converter.

public abstract class TableColumnName implements java.io.Serializable {
  public abstract <R,A> R accept(TableColumnName.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.reflection.lib.ddl.tbldecl.TblColumnName p, A arg);

  }

}
