package com.biosimilarity.reflection.lib.ddl.tbldecl; // Java Package generated by the BNF Converter.

public abstract class TableBoolean implements java.io.Serializable {
  public abstract <R,A> R accept(TableBoolean.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.reflection.lib.ddl.tbldecl.BoolLitTrue p, A arg);
    public R visit(com.biosimilarity.reflection.lib.ddl.tbldecl.BoolLitFalse p, A arg);

  }

}
