package com.biosimilarity.reflection.lib.ddl.tbldecl; // Java Package generated by the BNF Converter.

public abstract class TableColumnGTCtor implements java.io.Serializable {
  public abstract <R,A> R accept(TableColumnGTCtor.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.reflection.lib.ddl.tbldecl.TblColGTCtorBool p, A arg);
    public R visit(com.biosimilarity.reflection.lib.ddl.tbldecl.TblColGTCtorInt p, A arg);
    public R visit(com.biosimilarity.reflection.lib.ddl.tbldecl.TblColGTCtorStr p, A arg);

  }

}
