package com.biosimilarity.reflection.lib.ddl.tbldecl; // Java Package generated by the BNF Converter.

public abstract class TableMthdDecl implements java.io.Serializable {
  public abstract <R,A> R accept(TableMthdDecl.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.reflection.lib.ddl.tbldecl.TblColCtorMDecl p, A arg);
    public R visit(com.biosimilarity.reflection.lib.ddl.tbldecl.TblProjCtorMDecl p, A arg);

  }

}
