package com.biosimilarity.reflection.lib.ddl.tbldecl; // Java Package generated by the BNF Converter.

public class TblBody extends TableBody {
  public final ListTableMethodDecl listtablemethoddecl_;

  public TblBody(ListTableMethodDecl p1) { listtablemethoddecl_ = p1; }

  public <R,A> R accept(com.biosimilarity.reflection.lib.ddl.tbldecl.TableBody.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.reflection.lib.ddl.tbldecl.TblBody) {
      com.biosimilarity.reflection.lib.ddl.tbldecl.TblBody x = (com.biosimilarity.reflection.lib.ddl.tbldecl.TblBody)o;
      return this.listtablemethoddecl_.equals(x.listtablemethoddecl_);
    }
    return false;
  }

  public int hashCode() {
    return this.listtablemethoddecl_.hashCode();
  }


}
