package com.biosimilarity.reflection.lib.ddl.tbldecl; // Java Package generated by the BNF Converter.

public class TblColumnOptions extends TableColumnOptions {
  public final ListTableColumnOption listtablecolumnoption_;

  public TblColumnOptions(ListTableColumnOption p1) { listtablecolumnoption_ = p1; }

  public <R,A> R accept(com.biosimilarity.reflection.lib.ddl.tbldecl.TableColumnOptions.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.reflection.lib.ddl.tbldecl.TblColumnOptions) {
      com.biosimilarity.reflection.lib.ddl.tbldecl.TblColumnOptions x = (com.biosimilarity.reflection.lib.ddl.tbldecl.TblColumnOptions)o;
      return this.listtablecolumnoption_.equals(x.listtablecolumnoption_);
    }
    return false;
  }

  public int hashCode() {
    return this.listtablecolumnoption_.hashCode();
  }


}
