package com.biosimilarity.reflection.lib.ddl.tbldecl; // Java Package generated by the BNF Converter.

public class TblColumnGTCtor extends TableColumnCtor {
  public final TableColumnGTCtor tablecolumngtctor_;

  public TblColumnGTCtor(TableColumnGTCtor p1) { tablecolumngtctor_ = p1; }

  public <R,A> R accept(com.biosimilarity.reflection.lib.ddl.tbldecl.TableColumnCtor.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.reflection.lib.ddl.tbldecl.TblColumnGTCtor) {
      com.biosimilarity.reflection.lib.ddl.tbldecl.TblColumnGTCtor x = (com.biosimilarity.reflection.lib.ddl.tbldecl.TblColumnGTCtor)o;
      return this.tablecolumngtctor_.equals(x.tablecolumngtctor_);
    }
    return false;
  }

  public int hashCode() {
    return this.tablecolumngtctor_.hashCode();
  }


}
