package com.biosimilarity.reflection.lib.ddl.tbldecl; // Java Package generated by the BNF Converter.

public class TblCompType extends TableTypeDecl {
  public final TableCompositeType tablecompositetype_;

  public TblCompType(TableCompositeType p1) { tablecompositetype_ = p1; }

  public <R,A> R accept(com.biosimilarity.reflection.lib.ddl.tbldecl.TableTypeDecl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.reflection.lib.ddl.tbldecl.TblCompType) {
      com.biosimilarity.reflection.lib.ddl.tbldecl.TblCompType x = (com.biosimilarity.reflection.lib.ddl.tbldecl.TblCompType)o;
      return this.tablecompositetype_.equals(x.tablecompositetype_);
    }
    return false;
  }

  public int hashCode() {
    return this.tablecompositetype_.hashCode();
  }


}
