package com.biosimilarity.reflection.lib.ddl.tbldecl; // Java Package generated by the BNF Converter.

public class TblColumnArgs extends TableColumnArgs {
  public final String string_;
  public final TableColumnOptions tablecolumnoptions_;

  public TblColumnArgs(String p1, TableColumnOptions p2) { string_ = p1; tablecolumnoptions_ = p2; }

  public <R,A> R accept(com.biosimilarity.reflection.lib.ddl.tbldecl.TableColumnArgs.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.reflection.lib.ddl.tbldecl.TblColumnArgs) {
      com.biosimilarity.reflection.lib.ddl.tbldecl.TblColumnArgs x = (com.biosimilarity.reflection.lib.ddl.tbldecl.TblColumnArgs)o;
      return this.string_.equals(x.string_) && this.tablecolumnoptions_.equals(x.tablecolumnoptions_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.string_.hashCode())+this.tablecolumnoptions_.hashCode();
  }


}
