package com.biosimilarity.reflection.lib.ddl.tbldecl; // Java Package generated by the BNF Converter.

public class TblColumnDefault extends TableColumnOption {
  public final TableDefaultValue tabledefaultvalue_;

  public TblColumnDefault(TableDefaultValue p1) { tabledefaultvalue_ = p1; }

  public <R,A> R accept(com.biosimilarity.reflection.lib.ddl.tbldecl.TableColumnOption.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.reflection.lib.ddl.tbldecl.TblColumnDefault) {
      com.biosimilarity.reflection.lib.ddl.tbldecl.TblColumnDefault x = (com.biosimilarity.reflection.lib.ddl.tbldecl.TblColumnDefault)o;
      return this.tabledefaultvalue_.equals(x.tabledefaultvalue_);
    }
    return false;
  }

  public int hashCode() {
    return this.tabledefaultvalue_.hashCode();
  }


}
