package com.biosimilarity.reflection.lib.ddl.tbldecl; // Java Package generated by the BNF Converter.

public class TblColCtorDecl extends TableMethodDecl {
  public final TableColumnName tablecolumnname_;
  public final TableColumnCtor tablecolumnctor_;
  public final TableColumnArgs tablecolumnargs_;

  public TblColCtorDecl(TableColumnName p1, TableColumnCtor p2, TableColumnArgs p3) { tablecolumnname_ = p1; tablecolumnctor_ = p2; tablecolumnargs_ = p3; }

  public <R,A> R accept(com.biosimilarity.reflection.lib.ddl.tbldecl.TableMethodDecl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.reflection.lib.ddl.tbldecl.TblColCtorDecl) {
      com.biosimilarity.reflection.lib.ddl.tbldecl.TblColCtorDecl x = (com.biosimilarity.reflection.lib.ddl.tbldecl.TblColCtorDecl)o;
      return this.tablecolumnname_.equals(x.tablecolumnname_) && this.tablecolumnctor_.equals(x.tablecolumnctor_) && this.tablecolumnargs_.equals(x.tablecolumnargs_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.tablecolumnname_.hashCode())+this.tablecolumnctor_.hashCode())+this.tablecolumnargs_.hashCode();
  }


}
