package com.biosimilarity.reflection.lib.ddl.tbldecl; // Java Package generated by the BNF Converter.

public class TblDefaultValInt extends TableDefaultValue {
  public final Integer integer_;

  public TblDefaultValInt(Integer p1) { integer_ = p1; }

  public <R,A> R accept(com.biosimilarity.reflection.lib.ddl.tbldecl.TableDefaultValue.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.reflection.lib.ddl.tbldecl.TblDefaultValInt) {
      com.biosimilarity.reflection.lib.ddl.tbldecl.TblDefaultValInt x = (com.biosimilarity.reflection.lib.ddl.tbldecl.TblDefaultValInt)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
