package com.biosimilarity.reflection.lib.ddl.tbldecl; // Java Package generated by the BNF Converter.

public class TblGroundType extends TableTypeDecl {
  public final TableGroundType tablegroundtype_;

  public TblGroundType(TableGroundType p1) { tablegroundtype_ = p1; }

  public <R,A> R accept(com.biosimilarity.reflection.lib.ddl.tbldecl.TableTypeDecl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.reflection.lib.ddl.tbldecl.TblGroundType) {
      com.biosimilarity.reflection.lib.ddl.tbldecl.TblGroundType x = (com.biosimilarity.reflection.lib.ddl.tbldecl.TblGroundType)o;
      return this.tablegroundtype_.equals(x.tablegroundtype_);
    }
    return false;
  }

  public int hashCode() {
    return this.tablegroundtype_.hashCode();
  }


}
