package com.biosimilarity.reflection.lib.ddl.tbldecl; // Java Package generated by the BNF Converter.

public class TblProjCtorMDecl extends TableMthdDecl {
  public final ListIdent listident_;

  public TblProjCtorMDecl(ListIdent p1) { listident_ = p1; }

  public <R,A> R accept(com.biosimilarity.reflection.lib.ddl.tbldecl.TableMthdDecl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.reflection.lib.ddl.tbldecl.TblProjCtorMDecl) {
      com.biosimilarity.reflection.lib.ddl.tbldecl.TblProjCtorMDecl x = (com.biosimilarity.reflection.lib.ddl.tbldecl.TblProjCtorMDecl)o;
      return this.listident_.equals(x.listident_);
    }
    return false;
  }

  public int hashCode() {
    return this.listident_.hashCode();
  }


}
