package com.biosimilarity.reflection.lib.ddl.tbldecl; // Java Package generated by the BNF Converter.

public class TblProjCtorDecl extends TableMethodDecl {
  public final ListTableProjection listtableprojection_;

  public TblProjCtorDecl(ListTableProjection p1) { listtableprojection_ = p1; }

  public <R,A> R accept(com.biosimilarity.reflection.lib.ddl.tbldecl.TableMethodDecl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.reflection.lib.ddl.tbldecl.TblProjCtorDecl) {
      com.biosimilarity.reflection.lib.ddl.tbldecl.TblProjCtorDecl x = (com.biosimilarity.reflection.lib.ddl.tbldecl.TblProjCtorDecl)o;
      return this.listtableprojection_.equals(x.listtableprojection_);
    }
    return false;
  }

  public int hashCode() {
    return this.listtableprojection_.hashCode();
  }


}
