package com.biosimilarity.reflection.lib.ddl.tbldecl; // Java Package generated by the BNF Converter.

public class TblTypeDecls extends TableTypeDecls {
  public final ListTableTypeDecl listtabletypedecl_;

  public TblTypeDecls(ListTableTypeDecl p1) { listtabletypedecl_ = p1; }

  public <R,A> R accept(com.biosimilarity.reflection.lib.ddl.tbldecl.TableTypeDecls.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.reflection.lib.ddl.tbldecl.TblTypeDecls) {
      com.biosimilarity.reflection.lib.ddl.tbldecl.TblTypeDecls x = (com.biosimilarity.reflection.lib.ddl.tbldecl.TblTypeDecls)o;
      return this.listtabletypedecl_.equals(x.listtabletypedecl_);
    }
    return false;
  }

  public int hashCode() {
    return this.listtabletypedecl_.hashCode();
  }


}
